### ISSUE TITLE
My MP1

### ISSUE THREAD

**Issue by ShrimpyJ** [awelden0/MiniProject1#1]
@awelden0
My idea for mini project 1 is pretty straightforward. Similar to the example, I will plot a bar graph of the top 15 words from two books of the same author and two books from two different authors. For the same author I will use Dostoevsky's "Notes from the Underground" and "Crime and Punishment". For the differing authors I will compare "Notes from the Underground" to Robert W. Chambers's "The King in Yellow".

If you have any ideas on other ways to compare the data let me know, thanks!

**Comment by awelden0** [comment]
The bar plot idea sounds like it will work pretty well, I'm thinking about creating a frequency chart using a stem plot.
